language: java

install: true

addons:
  sonarcloud:
    organization: "kentico-github"
    token:
      secure: "uaN1jZNwY62H0Ga9XrQcWoHbhjIHWkVcT0oqj+SpCgHff2QgfLZKEQE31Q1Pe7rVjlzzzOZHnrWAndFfK5UO4ne8RVX8L4zctTUVml17XBQXNpoGGWD7Z3/TzBiSeytZAGB6Crc8n/Mr/CQsVATR8oGD3cKnIvNTeSJH2LE3Pw1SYuB8AyNkDLTF7AdEzxTgMuDCMIc7OyAYEC1RymwGw7Y1AvL+kaivckgfMkCr3NjCM/DcfdOfUm6/jm3DLaVGdyTgbjRH2aPA72NW++UP6Kgdx/0h08/ngEP2e88IG9ulU39NpLP4lIHlhQN0uiSxvfl2tv8NfJqCc0/CGnV+JOy+sJDgAImGu9Xg25OQZrPphjRGNoTYn8cLTbJ1S0sdimeDwpB8ceW/dzFSvKYbfuuLqpD4SpfWL2CbIKLgLDr+c6nxcDvPXafqIKDw/aUqPmoRVDLU1MTPevkHf4Pqg+GeSQdNv96MHxWXOIu8Td+jZjjR6kBh7QoEAaUZFYVYv0mOuaVMDQhjiCGMvQKFeeMSaTH6AL+CR7ozJIjII7hjT7SQU5KTq38Ss7Sgf2gG3C2tFks9C65/mnhr0w0vVDAtjFM3uvO0VzVeoFHBh6MYO2iU9ofSGd5G0p8xw03iPe1anPnMShx3R789VjWoB82nLxI88kvjUKbHZYpaiPA="

script:
  - ./gradlew sonarqube

before_cache:
  # remove all the artifacts (JAR, ZIP) that are installed in local repo because of gradle deploy
  - rm -f  $HOME/.gradle/caches/modules-2/modules2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.sonar/cache
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper
